version: '3.4'

services:
  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  inventoryapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  pizzeria:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

